import Head from "next/head";
import Feed from "src/component/Feed";

import Header from "src/component/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Feed */}
      <Feed />
    </>
  );
}
