import Head from "next/head";
import Feed from "src/component/Feed";

import Header from "src/component/Header";
import UploadModal from "src/component/UploadModal";

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link type="Image/x-icon" rel="icon" href="src/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Feed */}
      <Feed />
      {/* Modal Window */}
      <UploadModal />
    </>
  );
}
